# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Generate new localized screenshots"
  
lane :screenshots do
    snapshot(
      devices: ["iPhone 8 Plus"],
      languages: ["en-US"],
      #...
    )
  end

lane :tests do
  run_tests(workspace: "ComplexUIProject1.xcworkspace",
            devices: ["iPhone 8"],
            scheme: "ComplexUIProject1")
end
lane :gitpush do

        git_add
        git_commit(path: "*", message: "Version")
        push_to_git_remote


end
end
